{{- if .Values.platformApi.rateLimit.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rate-limits
  namespace: {{ .Values.platformApi.namespace }}
data:
  limits.yaml: |
{{ .Values.platformApi.rateLimit.config | indent 4 }}
{{- end }}
