{{- if .Values.platformApi.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.platformApi.app.name }}
  namespace: {{ .Values.platformApi.namespace }}
  labels:
    app: {{ .Values.platformApi.app.name }}
    {{- with .Values.platformApi.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: metrics
      interval: {{ .Values.platformApi.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.platformApi.serviceMonitor.scrapeTimeout }}
  namespaceSelector:
    matchNames:
      - {{ .Values.platformApi.namespace }}
  selector:
    matchLabels:
      app: {{ .Values.platformApi.app.name }}
{{- end }}
