apiVersion: v1
kind: ServiceAccount
metadata:
  name: sigv4-proxy-logs
  namespace: vector
  labels:
    app.kubernetes.io/name: sigv4-proxy-logs
    app.kubernetes.io/component: logs-proxy
    app.kubernetes.io/part-of: observability
