hyperfleet:
  applicationName: hyperfleet-operator

  namespace: argocd

  targetNamespace: hyperfleet

  project: default

  source:
    repoURL: https://github.com/openshift-online/rosa-hyperfleet-api.git
    targetRevision: f7ec7d59ed8523bc66277cce3f4814e0dee5fa83
    path: hyperfleet-operator/charts

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  helmValues:
    image:
      repository: quay.io/redhat-user-workloads/rosa-tenant/hyperfleet-operator
      tag: "f7ec7d59ed8523bc66277cce3f4814e0dee5fa83"
      pullPolicy: Always

    replicaCount: 2

    serviceAccount:
      create: true
      name: hyperfleet-operator
      annotations: {}

    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
